// ============================================================
// Centralized projects data loader
// ============================================================
// Loads project data from data/projects-data.json (generated by
// GitHub Actions) at runtime. Falls back to empty categories if
// the JSON is unavailable.
//
// Each project entry in the JSON has i18n fields:
//   title: { pt, en }, description: { pt, en }
// The rendering layer (projects.js) resolves these via i18n.
// ============================================================

// Mutable — will be populated by loadProjectsData()
export const projectsData = {
  offensive: [],
  defensive: [],
  reports: [],
  ai: [],
  networking: [],
  software: [],
  web: [],
  hardware: [],
};

// Metadata from the JSON
export let projectsLastUpdated = '';

/**
 * Fetches data/projects-data.json and populates projectsData.
 * Returns true if loaded successfully, false otherwise.
 */
export async function loadProjectsData() {
  try {
    const res = await fetch('./data/projects-data.json');
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();

    // Populate categories
    const categories = ['offensive', 'defensive', 'reports', 'ai', 'networking', 'software', 'web', 'hardware'];
    for (const cat of categories) {
      if (Array.isArray(data.projects?.[cat])) {
        projectsData[cat] = data.projects[cat];
      }
    }

    projectsLastUpdated = data.lastUpdated || '';
    console.log(`📦 Loaded ${categories.reduce((s, c) => s + projectsData[c].length, 0)} projects (updated: ${projectsLastUpdated})`);
    return true;
  } catch (err) {
    console.warn('⚠ Could not load projects-data.json, using empty data:', err.message);
    return false;
  }
}
